### ISSUE TITLE
how provide callback before send images?

### ISSUE THREAD

**Issue by SecretKeeper** [fxmontigny/quill-image-upload#1]
how can i use callbacks before sending image to server?
i wanna build a confirmation by user before send images

thanks

**Comment by fxmontigny** [comment]
Hi,

Interesting. Actually you can't do this. 
A can add this option but not today sorry. Probably at the end of the week.

**Comment by SecretKeeper** [comment]
Nice , ok
Ill wait end od week

Thanks

**Comment by fxmontigny** [comment]
Just for you.
Release 0.1.2
https://github.com/fxmontigny/quill-image-upload/releases/tag/v0.1.2

```
// optional
            // add callback when a image have been chosen
            checkBeforeSend: (file, next) => {
                console.log(file);
                next(file); // go back to component and send to the server
            }
```
