### ISSUE TITLE
Enhancement: Ability to show progress/loader

### ISSUE THREAD

**Issue by royshouvik** [fxmontigny/quill-image-upload#2]
Thanks for getting this up. Worked out of the box like a charm!

Since uploading to server takes some amount of time, it would be nice to show some feedback to the user.

**Comment by fxmontigny** [comment]
Hi, 

you cannont show progressive loader but only when the loading start and finish. 
```
checkBeforeSend: (file, next) => {
     // show loader
    next(file); // go back to component and send to the server
}


callbackOK: (serverResponse, next) => {
     // hide loader
    next(serverResponse);   
},
    
callbackKO: (serverError) => {
    // hide loader
    alert(serverError);
},
```

**Comment by royshouvik** [comment]
I ended up doing something like that just after posting this question. Thanks 👍
